spring.application.name=backend
server.port=8080

# Active profile (can be overridden via ENV or command line args)
spring.profiles.active=dev

# Common Supabase JWT Secret
supabase.jwt.secret=${SUPABASE_JWT_SECRET}

# Common Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
